curl https://d2qg3tx5cpup36.cloudfront.net/dark/camera_shape_WoBatteryCam.png -O 
curl https://d2qg3tx5cpup36.cloudfront.net/dark/camera_shape_WoCamera.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/camera_shape_WoCamKvs.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/camera_shape_WoCamKvs5mp.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/camera_shape_WoOSC2.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/camera_shape_WoPanTiltCam.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/camera_shape_WoPanTiltCam3MP.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/camera_shape_W1050000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/camera_shape_W1050001.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/camera_shape_W1050002.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/camera_type_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/camera_type_privacy.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/camera_type_doorbell_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/camera_type_doorbell_privacy.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/curtain_shape_WoBlindTilt.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/curtain_shape_WoCurtain.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/curtain_shape_WoCurtain3.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/curtain_shape_WoRollerShade.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/curtain_type_bindtilt_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/curtain_type_bindtilt_on.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/curtain_type_version1_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/curtain_type_group_version1_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/curtain_type_group_version1_on.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/curtain_type_version1_on.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/curtain_type_rollershade_off.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/curtain_type_rollershade_on.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/curtain_type_rollershade_some_on.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/unknown_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_shape_WoAirPurifier.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_shape_WoAirPurifierPro.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_shape_WoAirPurifierJP.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_shape_WoAirPurifierUS.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_shape_WoAirPurifierJPPro.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_shape_WoAirPurifierUSPro.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_shape_WoFan.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_shape_WoFan2.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_shape_W1116000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_shape_WoHumi.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_shape_WoHumi2.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_shape_WoHumi2Plus.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_type_fan_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_type_fan_on.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_type_humi_defalut.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_type_humi_on.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_type_humi2_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_type_humi2_on.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_type_purifier_0.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_type_purifier_1.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_type_purifier_2.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_type_purifier_3.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/env_type_purifier_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/hub_type_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/hub_type_temperature_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/hub_type_humidity_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/hub_type_temperature_alarm.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/hub_type_humidity_alarm.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/hub_type_abs_humidity_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/hub_type_abs_humidity_alarm.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/hub_shape_WoLinkMini.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/hub_shape_WoLinkPlus.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/hub_shape_WoHub2.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/hub_shape_WoLinkMatter.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/hub_shape_W1096000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/hub_shape_W1095000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_type_1.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_type_2.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_type_3.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_type_4.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_type_5.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_type_6.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_type_7.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_type_8.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_type_9.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_type_10.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_type_11.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_type_12.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_type_13.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_type_14.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_shape_1.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_shape_2.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_shape_3.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_shape_4.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_shape_5.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_shape_6.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_shape_7.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_shape_8.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_shape_9.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_shape_10.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_shape_11.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_shape_12.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_shape_13.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/ir_shape_14.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_shape_WoBulb.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_shape_WoCeiling.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_shape_WoCeilingPro.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_shape_WoStrip.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_type_icon_32pt_ceilinglamp_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_type_icon_32pt_ceilinglamp_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_type_icon_32pt_desklamp_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_type_icon_32pt_desklamp_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_type_icon_32pt_floorlamp_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_type_icon_32pt_floorlamp_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_type_icon_32pt_light_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_type_icon_32pt_light_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_type_icon_32pt_lightstrip_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_type_icon_32pt_lightstrip_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_shape_W1102000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_type_icon_32pt_W1102000_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_type_icon_32pt_W1102000_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_shape_W1102001.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_shape_W1102002.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_shape_W1102003.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_shape_W1102004.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_shape_W1102005.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/light_shape_W1123000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/lock_shape_WoLock.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/lock_shape_WoLockPro.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/lock_shape_WoLockLite.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/lock_shape_W1091000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/lock_shape_WoLockPro.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/lock_type_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/lock_type_unlocked.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/remote_shape_WoButton.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/remote_shape_WoRWS.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/remote_type_WoButton.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/remote_type_WoRWS.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_shape_WoContact.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_shape_WoIOSensor.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_shape_WoMeter.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_shape_WoMeterPlus.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_shape_WoPresence.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_shape_W1079000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_shape_W1079001.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_shape_WoWaterDetector.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_shape_W1111000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_humidity_alarm.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_humidity_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_abs_humidity_alarm.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_abs_humidity_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_icon_32pt_contact_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_icon_32pt_contact_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_icon_32pt_doors_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_icon_32pt_doors_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_icon_32pt_motion_version1_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_icon_32pt_motion_version1_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_icon_32pt_windows_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_icon_32pt_windows_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_meter_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_temperature_alarm.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_temperature_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_waterdetector_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_waterdetector_in_alarm.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_waterdetector_in_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_waterdetector_out_alarm.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_waterdetector_out_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_co2_level_good.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_co2_level_mid.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_co2_level_low.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_meter_pro_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_type_meter_pro_co2_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_shape_W1113000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_shape_tpqXG5pD.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_shape_91AgWZ1n.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_shape_WoSweeperMini.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_shape_WoSweeper.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_shape_WoSweeperMini.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_shape_WoSweeperMiniPro.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_shape_WoSweeperOrigin.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_shape_WoSweeperPlus.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_type_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_type_on.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_type_platform_no_comb_offline.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_type_platform_no_comb_online.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_type_platform_comb_offline.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_type_platform_comb_online.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_shape_W1106000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sweeper_shape_W1107000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_socket_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_socket_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_lightstrip_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_lightstrip_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_light_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_light_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_coffeemachine_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_coffeemachine_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_floorlamp_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_floorlamp_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_desklamp_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_desklamp_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_ceilinglamp_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_ceilinglamp_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_bathtub_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_bathtub_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_switch_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_switch_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_television_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_television_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_boiler_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_boiler_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_heater_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_heater_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_cooler_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_cooler_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_washer_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_washer_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_fridge_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_fridge_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_cookware_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_cookware_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_pool_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_pool_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_ventilator_highlight.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_32pt_ventilator_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_2pm_all_off.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_2pm_all_on.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_2pm_on1.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_2pm_on2.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_2pm_rollershade_off.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_2pm_rollershade_on.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_2pm_rollershade_some_on.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_gdo_opened.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_type_icon_gdo_closed.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_shape_W1083000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_shape_W1083001.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_shape_W1083002.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_shape_W1083003.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_shape_W1104000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_shape_WoPlugUS.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_shape_WoHand.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_shape_WoPlug.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/switch_shape_WoPlugJP.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/tag_shape_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_shape_WoFinderCard.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_shape_WoKeypad.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_shape_WoKeypadTouch.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_shape_W1115000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_shape_W1110000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_briefcase.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_briefcase.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_cat.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_cat.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_child.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_child.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_dog.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_dog.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_elder.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_elder.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_handbag.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_handbag.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_headset.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_headset.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_key.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_key.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_leave_home.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_phone.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_phone.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_trunk.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_trunk.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_wallet.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_fc_wallet.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_keypad_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/doorbellIndoor_type_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/doorbellOutdoor_type_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_safety_alarm_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/key_type_icon_32pt_safety_alarm_leave_home.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/sensor_shape_W1101000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/aiPet_shape_W1121000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/aiPet_type_default.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/aiPet_type_happy.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/aiPet_type_sleep.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/auto_shape_W1128000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/auto_shape_W1128000.png -O
curl https://d2qg3tx5cpup36.cloudfront.net/dark/auto_type_W1128000_on.png -O